baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[services]
  [services.googleAnalytics]
    ID = 'G-88X2LKWJJG'

[module]
[[module.imports]]
    path = 'github.com/hugomods/google-adsense'