baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[services]
  [services.googleAnalytics]
    ID = 'G-88X2LKWJJG'

[params]
  google_adsense = 'ca-pub-7002754731502832'